services:
  app:
    build: .
    environment:
      PHX_HOST: ${PHX_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    ports:
      - "4000:4000"
    networks:
      - reverse-proxy
    restart: unless-stopped

networks:
  reverse-proxy:
    external: true
